version: 0.0
os: linux
files:
  - source: /vendor/
    destination: /home/ec2-user/serverpod/upload/vendor/
  - source: /community_hub_server/
    destination: /home/ec2-user/serverpod/upload/community_hub_server/
hooks:
  BeforeInstall:
    - location: community_hub_server/deploy/aws/scripts/install_dependencies
      timeout: 300
      runas: root
  ApplicationStart:
    - location: community_hub_server/deploy/aws/scripts/start_server
      timeout: 300
      runas: root
